# Generated by Django 2.2.9 on 2020-02-07 16:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import map_quest.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=2048, verbose_name='Label')),
                ('description', models.TextField(verbose_name='Description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=map_quest.models.Dataset.logo_dir, verbose_name='Logo')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Crée le')),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=7, null=True, verbose_name='Couleur')),
                ('is_active', models.BooleanField(default=True, verbose_name='Est valide')),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326, verbose_name='Ligne')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=2048, verbose_name='Label')),
                ('color', models.CharField(blank=True, max_length=7, null=True, verbose_name='Couleur')),
                ('is_active', models.BooleanField(default=True, verbose_name='Est valide')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='POI')),
            ],
        ),
        migrations.CreateModel(
            name='Subset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=7, null=True, verbose_name='Couleur par défaut')),
                ('context', models.TextField(verbose_name='Contexte')),
                ('attachement', models.FileField(blank=True, null=True, upload_to=map_quest.models.Subset.attachement_dir, verbose_name='Fichier joint')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsets', to='map_quest.Dataset')),
                ('edges', models.ManyToManyField(to='map_quest.Edge')),
                ('nodes', models.ManyToManyField(to='map_quest.Node')),
            ],
        ),
    ]
