# Generated by Django 2.2.9 on 2020-02-11 14:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_quest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=2048, null=True, verbose_name='Label')),
                ('color', models.CharField(blank=True, max_length=7, null=True, verbose_name='Couleur')),
                ('is_active', models.BooleanField(default=True, verbose_name='Est valide')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Ligne')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='edge',
            name='label',
            field=models.CharField(max_length=2048, null=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='node',
            name='label',
            field=models.CharField(max_length=2048, null=True, verbose_name='Label'),
        ),
        migrations.AddField(
            model_name='subset',
            name='polygones',
            field=models.ManyToManyField(to='map_quest.Polygon'),
        ),
    ]
