# Generated by Django 2.2.9 on 2020-02-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_quest', '0002_auto_20200211_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='label',
            field=models.CharField(max_length=2048, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='node',
            name='label',
            field=models.CharField(max_length=2048, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='label',
            field=models.CharField(max_length=2048, verbose_name='Label'),
        ),
    ]
