# Generated by Django 2.2.9 on 2020-02-11 14:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_quest', '0003_auto_20200211_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Zones'),
        ),
    ]
