# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-11-25 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='legal_name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Dénomination sociale'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
