# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-01-23 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sid', '0002_auto_20191125_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='sid_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sid_id',
        ),
    ]
