#!/bin/sh

psql -U postgres -c "CREATE USER $POSTGRES_USER PASSWORD '$POSTGRES_PASSWORD'"
psql -U postgres -c "CREATE DATABASE $POSTGRES_DB OWNER $POSTGRES_USER"
psql -U postgres -c "CREATE SCHEMA IF NOT EXISTS $POSTGRES_SCHEMA1 AUTHORIZATION $POSTGRES_USER"
psql -U postgres -c "CREATE SCHEMA IF NOT EXISTS $POSTGRES_SCHEMA2 AUTHORIZATION $POSTGRES_USER"
psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER"
